# Generated by Django 4.2.3 on 2023-07-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_lan',
            new_name='event_lon',
        ),
    ]
