# Generated by Django 4.2.3 on 2023-07-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0003_rename_userid_events_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='user_id',
            new_name='owner',
        ),
    ]
