# Generated by Django 4.2.3 on 2023-07-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0004_rename_user_id_events_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='owner',
        ),
    ]
