# Generated by Django 4.2.3 on 2023-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0005_remove_events_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_lon',
            field=models.FloatField(),
        ),
    ]
