# Generated by Django 4.2.3 on 2023-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0007_events_event_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_country',
            field=models.CharField(max_length=64),
        ),
    ]
