# Generated by Django 4.2.3 on 2023-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0009_weatherevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherevent',
            name='event_id',
            field=models.CharField(default='2', max_length=64),
        ),
    ]
