# Generated by Django 4.2.3 on 2023-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0011_alter_weatherevent_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights_going', models.JSONField()),
                ('flights_backhome', models.JSONField()),
            ],
        ),
    ]
