# Generated by Django 4.2.3 on 2023-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0012_flightlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlist',
            name='event_id',
            field=models.CharField(default='21', max_length=64),
        ),
    ]
