# Generated by Django 4.2.3 on 2023-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsAPI', '0013_flightlist_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlist',
            name='event_id',
            field=models.CharField(max_length=64),
        ),
    ]
